name: PyTest

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_3-10_windows:
    name: Test on Windows with Python 3.10
    runs-on: windows-latest

    env:
      OPENCVE_USERNAME: ${{ secrets.OPENCVE_USERNAME }}
      OPENCVE_PASSWORD: ${{ secrets.OPENCVE_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-asyncio
        python -m pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest

  test_3-10_ubuntu:
    name: Test on Ubuntu with Python 3.10
    runs-on: ubuntu-latest
    needs: test_3-10_windows

    env:
      OPENCVE_USERNAME: ${{ secrets.OPENCVE_USERNAME }}
      OPENCVE_PASSWORD: ${{ secrets.OPENCVE_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-asyncio
        python -m pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest

  test_3-11_windows:
    name: Test on Windows with Python 3.11
    runs-on: windows-latest
    needs: test_3-10_ubuntu

    env:
      OPENCVE_USERNAME: ${{ secrets.OPENCVE_USERNAME }}
      OPENCVE_PASSWORD: ${{ secrets.OPENCVE_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-asyncio
        python -m pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest

  test_3-11_ubuntu:
    name: Test on Ubuntu with Python 3.11
    runs-on: ubuntu-latest
    needs: test_3-11_windows

    env:
      OPENCVE_USERNAME: ${{ secrets.OPENCVE_USERNAME }}
      OPENCVE_PASSWORD: ${{ secrets.OPENCVE_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-asyncio
        python -m pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest
